name: CD Workflow DEMO REACT APP

on:
  workflow_run:
    workflows: ["CI Workflow DEMO REACT APP"]
    types:
      - completed

jobs:
  cd:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Deployment workflow has been initiated
        run: echo "Deployment workflow has been initiated!"

      - name: Set target bucket based on branch
        id: set-bucket
        run: |
            BRANCH="${{ github.event.workflow_run.head_branch }}"
            echo "Detected branch: $BRANCH"

            if [[ "$BRANCH" == feature/* ]]; then
               echo "bucket=react-dev-app-v1" >> $GITHUB_OUTPUT
               echo "env=Development" >> $GITHUB_OUTPUT
            
            elif [[ "$BRANCH" == "develop" ]]; then
               echo "bucket=react-test-app-v1" >> $GITHUB_OUTPUT
               echo "env=Test" >> $GITHUB_OUTPUT

            elif [[ "$BRANCH" == "main" ]]; then
               echo "bucket=react-prod-app-v1" >> $GITHUB_OUTPUT
               echo "env=Production" >> $GITHUB_OUTPUT
            else
               echo "Unknown branch: $BRANCH"
               exit 1
            fi
      - name: Deploy to S3 (${{ steps.set-bucket.outputs.env }})
        run: |
          echo "Deploying to bucket: ${{ steps.set-bucket.outputs.bucket }}"
          aws s3 sync build/ s3://${{ steps.set-bucket.outputs.bucket }} --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}