name: CD Workflow (DEMO REACT APP)

on:
  push:
    branches:
      - feature/**
    paths-ignore:
      - '.github/workflows/**'
  pull_request:
    branches:
      - develop
      - main
    paths-ignore:
      - '.github/workflows/**'


jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - name: Deployment workflow has been initiated
        run: echo "Deployment workflow has been initiated!" 
