name: CD Workflow (DEMO REACT APP)

on:
  workflow_run:
    workflows: ["CI Workflow (DEMO REACT APP)"]
    types:
      - completed

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - name: Deployment workflow has been initiated
        run: echo "Deployment workflow has been initiated!" 
