name: CD Workflow DEMO REACT APP

on:
  workflow_run:
    workflows: ["CI Workflow DEMO REACT APP"]
    types:
      - completed

jobs:
  cd:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: ${{ 
                    github.ref == 'refs/heads/main' && 'prod' || 
                    github.ref == 'refs/heads/develop' && 'test' || 
                    startsWith(github.ref, 'refs/heads/feature/') && 'dev' || 
                    'default' 
                  }}
 

    steps:
      - name: Deployment workflow has been initiated
        run: echo "Deployment workflow has been initiated!"

      - name: Set target bucket based on branch
        id: extract
        run: |
            BRANCH="${{ github.event.workflow_run.head_branch }}"
            echo "Detected branch: $BRANCH"

            if [[ "$BRANCH" == feature/* ]]; then
               echo "deploy_bucket=react-dev-app-v1" >> $GITHUB_OUTPUT
               ENV="dev"
                
            elif [[ "$BRANCH" == "develop" ]]; then
               echo "deploy_bucket=react-test-app-v1" >> $GITHUB_OUTPUT
               ENV="test"

            elif [[ "$BRANCH" == "main" ]]; then
               echo "deploy_bucket=react-prod-app-v1" >> $GITHUB_OUTPUT
               ENV="prod"
            else
               echo "Unknown branch: $BRANCH"
               exit 1
            fi

            BUCKET="react-${ENV}-artifact-bucket"
            echo "env=$ENV" >> $GITHUB_OUTPUT
            echo "bucket=$BUCKET" >> $GITHUB_OUTPUT

      - name: Download build from S3 bucket
        run: |
          aws s3 sync s3://${{ steps.extract.outputs.bucket }}/ ./build
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.REGION }}

      - name: Deploy build to S3 (deployment bucket)
        run: |
          aws s3 sync ./build s3://${{ steps.extract.outputs.deploy_bucket }}/ --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.REGION }}
