name: CD Workflow

on:
  workflow_run:
    workflows: ["CI Workflow"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Download build from S3
        run: |
          SHA=${{ github.event.workflow_run.head_sha }}
          aws s3 sync s3://react-dev-artifact-bucket/$SHA ./build --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1

      - name: Determine S3 target bucket
        id: vars
        run: |
          BRANCH="${{ github.event.workflow_run.head_branch }}"
          if [[ "$BRANCH" == "dev" ]]; then
            echo "bucket=your-react-app-dev" >> $GITHUB_OUTPUT
          elif [[ "$BRANCH" == "test" ]]; then
            echo "bucket=your-react-app-dev" >> $GITHUB_OUTPUT
          elif [[ "$BRANCH" == "main" ]]; then
            echo "bucket=your-react-app-dev" >> $GITHUB_OUTPUT
          else
            echo "Invalid branch"
            exit 1
          fi

      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: ${{ steps.vars.outputs.bucket }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
          SOURCE_DIR: build
