name: CD Pipeline

on:
  workflow_dispatch:

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build React App
        run: npm run build

      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region your-region

      - name: Deploy to S3
        run: |
          BRANCH_NAME=$(echo $GITHUB_REF | sed 's/refs\/heads\///')
          if [[ "$BRANCH_NAME" == "develop" ]]; then
            aws s3 sync build/ s3://your-dev-bucket --delete
          elif [[ "$BRANCH_NAME" == "test" ]]; then
            aws s3 sync build/ s3://your-test-bucket --delete
          elif [[ "$BRANCH_NAME" == "main" ]]; then
            aws s3 sync build/ s3://your-prod-bucket --delete
          fi
