name: CI Workflow DEMO REACT APP

on:
  push:
    branches:
      - feature/**
    paths-ignore:
      - '.github/workflows/**'
  pull_request:
    branches:
      - develop
    paths-ignore:
      - '.github/workflows/**'
  workflow_dispatch:


jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Download GitHub repository’s code into the GitHub action runner so that workflow can use it
        uses: actions/checkout@v4

      - name: Setup Node JS in the GitHub action runner
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Installing dependencies
        run: npm install

      - name: Running test cases
        run: npm test

      - name: Creating Build
        run: npm run build

      - name: Extract branch and set env/bucket
        id: extract
        run: |
            BRANCH="${GITHUB_REF#refs/heads/}"
            echo "Detected branch: $BRANCH"

            if [[ "$BRANCH"  =~ ^feature/.* ]]; then
               echo "ENV=dev" >> $GITHUB_OUTPUT
               echo "dev env"
            
            elif [[ "$BRANCH" == "develop" ]]; then
               echo "ENV=test" >> $GITHUB_OUTPUT
               echo "test env"

            elif [[ "$BRANCH" == "main" ]]; then
               echo "ENV=prod" >> $GITHUB_OUTPUT
            else
               echo "Unknown branch: $BRANCH"
               exit 1
            fi

            BUCKET="react-${ENV}-artifact-bucket"
            echo "env=$ENV" >> $GITHUB_OUTPUT
            echo "bucket=$BUCKET" >> $GITHUB_OUTPUT
            echo "Detected bucket: $BUCKET"


      - name: Upload build to temporary S3
        run: |
          aws s3 sync build/ s3://${{ steps.extract.outputs.bucket }}/ --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}