name: CI Workflow

on:
  push:
    branches:
      - 'feature/**'
    paths-ignore:
      - '.github/workflows/**'
  pull_request:
    branches:
      - develop
      - main
    paths-ignore:
      - '.github/workflows/**'

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm install
      - run: npm test
      - run: npm run build
