name: CI Workflow (DEMO REACT APP)

on:
  push:
    branches:
      - 'feature/**'
    paths-ignore:
      - '.github/workflows/**'
  pull_request:
    branches:
      - develop
      - main
    paths-ignore:
      - '.github/workflows/**'

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Download GitHub repository’s code into the GitHub action runner so that workflow can use it
        uses: actions/checkout@v4

      - name: Setup Node JS in the GitHub action runner
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Installing dependencies
        run: npm install

      - name: Running test cases
        run: npm test

      - name: Creating Build
        run: npm run build
